POST http://localhost:3001/api/user HTTP/1.1
content-type: application/json 

{
  "email": "osses@gmail.com",
  "password": "wwwuyw",
  "firstname": "osses",
  "minit": "",
  "lastname": "baah"
} 
###
POST http://localhost:3001/api/payment HTTP/1.1
content-type: application/json 



{
  "description": "awa",
  "qty": 3,
  "price": 500,
  "Total": 1000,
  "user": "634af40c4b1ae0caf14bc294"
}








